name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm run package
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        input:
          - name: nixpkgs
            repo: nixpkgs
            owner: NixOS

          - name: pre-commit-hooks
            repo: pre-commit-hooks.nix
            owner: cachix
    steps:
      - uses: actions/checkout@v3

      - name: test
        uses: ./
        id: test
        with:
          input: ${{ matrix.input.name }}

      - name: check owner
        run: if [ "${{ steps.test.outputs.owner }}" != "${{ matrix.input.owner }}" ]; then exit 1; fi

      - name: check repo
        run: if [ "${{ steps.test.outputs.repo }}" != "${{ matrix.input.repo }}" ]; then exit 1; fi

      - name: check rev
        run: if [ -z "${{ steps.test.outputs.rev }}" ]; then exit 1; fi

      - name: check short-rev
        run: if [ -z "${{ steps.test.outputs.short-rev }}" ]; then exit 1; fi
  release:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: cycjimmy/semantic-release-action@v3.4.1
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/github
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
