name: Update Dependencies
on:
  schedule:
    - cron: "20 */6 * * *"
  workflow_dispatch:
jobs:
  flake-update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        input:
          - nixpkgs
          - pre-commit-hooks
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable-small
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cpcloud/flake-dep-info-action@main
        id: get_current_commit
        with:
          input: ${{ matrix.input }}

      - run: nix flake lock --update-input ${{ matrix.input }}

      - uses: cpcloud/flake-dep-info-action@main
        id: get_new_commit
        with:
          input: ${{ matrix.input }}

      - uses: cpcloud/compare-commits-action@v5.0.13
        id: compare_commits
        if: ${{ steps.get_current_commit.outputs.rev != steps.get_new_commit.outputs.rev }}
        with:
          owner: ${{ steps.get_new_commit.outputs.owner }}
          repo: ${{ steps.get_new_commit.outputs.repo }}
          basehead: ${{ steps.get_current_commit.outputs.rev }}...${{ steps.get_new_commit.outputs.rev }}
          token: ${{ secrets.GITHUB_TOKEN }}
          include-merge-commits: false

      - uses: tibdex/github-app-token@v1
        if: ${{ steps.get_current_commit.outputs.rev != steps.get_new_commit.outputs.rev }}
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: peter-evans/create-pull-request@v3
        if: ${{ steps.get_current_commit.outputs.rev != steps.get_new_commit.outputs.rev }}
        id: create_pr
        with:
          commit-message: "chore(deps): update ${{ matrix.input }}"
          branch: "create-pull-request/update-${{ matrix.input }}"
          delete-branch: true
          author: "Phillip Ground <cpcloudbot@gmail.com>"
          title: "chore(deps): update ${{ matrix.input }}"
          token: ${{ steps.generate_token.outputs.token }}
          body: ${{ steps.compare_commits.outputs.differences }}
          labels: dependencies,autorebase:opt-in

      - uses: peter-evans/enable-pull-request-automerge@v1
        if: ${{ steps.create_pr.outputs.pull-request-operation == 'created' }}
        with:
          token: ${{ steps.generate_token.outputs.token }}
          pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
          merge-method: rebase
